# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy app in dev enviroment"
  lane :deploy_dev do
    # add actions here: https://docs.fastlane.tools/actions
    puts "Slack channel: #{ENV['SLACK_CHANNEL']}"
    puts "apk dir: #{ENV['APK_DIR']}"

    gradle(
      task: "assemble",
      build_type: "Debug",
      project_dir: "./android"
    )
  end
end
